### ISSUE TITLE
Nematic order parameter giving seemingly opposite results.

### ISSUE THREAD

**Issue by jbieri** [cmelab/SIC#3]
On the add-nematic-order branch in the preliminary-work directory; the Problem.ipynb shows that calculating the S2 parameter for each molecule corresponds to decreasing order during a tensile test. Conversely calculating S2 for every atom regardless of which molecule it's in shows a very clear increase as expected. Why might this be the case?
@erjank @marjanalbooyeh @chrisjonesBSU

**Comment by jbieri** [comment]
First frame versus final frame of the gsd file in question.

![image](https://github.com/user-attachments/assets/2c5beae4-c683-496c-bb84-75cf1b0b3077)

![image](https://github.com/user-attachments/assets/831f45ad-c629-40e6-a54e-05a97d2209d3)

**Comment by StephMcCallum** [comment]
Hi @jbieri, could you add more comments to this section of code?

`def nop(frame):
    positions = frame.particles.position
    molecule_ids = frame.bonds.group
    temp = positions[0]
    vectors = []
    for i, pos in enumerate(positions):
            if i < len(molecule_ids):
                vectors.append(np.stack(pos) - np.stack(temp))
                temp = pos
    vectors = np.array(vectors[1:])
    return vectors`

I think the goal here would be to define a vector for each molecule by using the position of each particle in the molecule. I added a few print statements and I don't think that is what this code is achieving because the length of positions and vectors is the same. We may need to access the molecule groups from the gsd file in a different way.

**Comment by jbieri** [comment]
I'll get on that when I get back home around 9, and thank you for the advice. Do you mean that the length of the arrays of positions and vectors are the same? I have been trying to find examples of people using this in literature in addition to reading the docs again, but I haven't been successful thus far.

**Comment by StephMcCallum** [comment]
Yes, those are the two vectors I meant. Question, for the nematic order, don't we want to compare a positional vector of each compound, with each frame having separate positional vectors? I think right now the vector you are calculating is the position difference between frames.

**Comment by jbieri** [comment]
The nop function is entirely based within one frame with the loop through every frame in the trajectory occuring in the code for both of the methods. For method 1 the nop function is used exclusively to get orientational vectors between atoms within molecules (I just realized that I should add exceptions or cases for when swapping between the last atom of 1 molecule and the first of the next). This is in contrast with method 2 whereby I let freud do the calculation of orientations for me (not sure if this method gives the exact correct S2 parameter but it does show the correct trend).
